### Site info:
title: For changing myself first
tagline: Keep it simple, stupid!  (paper for idea - CLI for coding - GUI for end user only)
author: Giang Do (Đỗ Trường Giang)
email: dotruonggiang108@gmail.com
description: "My blog is used to change myself first!" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "electronic, embedded, linux, điện tử, nhúng"
#baseurl: "/freshman21" # the subpath of your site, e.g. /blog
url: "http://giangdo.github.io" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: giangdo 
github_username: giangdo 
disqus_shortname: giangdo 
favicon:     "/images/favicon.ico"
aboutme: Hi, this is Giang Do. I'm Vietnamese. I'm inpired by opensource idea about electronic, Internet of Things and Linux. # these are shown on aboutme-sidebar.
aboutme_photo: https://i.imgur.com/Mdc4szJl.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: giangdo
      href: http://giangdo.github.io/
      title: Giang Do's blog 
    - name: author's website
      href: http://giangdo.github.io/
      title: Giang Do's blog


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
